### ISSUE TITLE
Cannot read property 'uid' of undefined

### ISSUE THREAD

**Issue by mettamyron** [juristr/kudos#2]
I get a "Cannot read property 'uid' of undefined" off the console log at:

```
getAuthData().then(function(authData){
            firebaseKudos.child(key).child('likes').child(authData.uid).once('value', function(snap){
                deferred.resolve(snap.val() !== null);
            });
```
What should I change it to to align with the new firebase functions?

**Comment by juristr** [comment]
Hey, I'm sorry but I'm not using this library any more. The error is most probably due to changes in the Firebase API I guess. You'd have to look that up.

It might also be a bug though, cannot exclude that. But as said, given that I don't use it any more, I don't have time to go fix it, sorry :)
